If we catch this error : 

2024-08-30 00:36:30 - ERROR tracker: ** [LSD] **, name: John Wick Chapter 4 (2023) MULTi VFF 2160p 10bit 4KLight DV HDR BluRay TrueHD Atmos 7.1 x265-QTZ.mkv, downloading_torrents : {}
Traceback (most recent call last):
  File "/home/diego/htpc-download-box/qbit_api_8080/main.py", line 325, in <module>
    monitor_torrents()
  File "/home/diego/htpc-download-box/qbit_api_8080/main.py", line 271, in monitor_torrents
    tracker = get_trackers(torrent, hash_string, downloading_torrents)
  File "/home/diego/htpc-download-box/qbit_api_8080/main.py", line 60, in get_trackers
    raise ValueError(f"{tracker} isn't a valid tracker. You need to reassign manually the tracker of '{torrent['name']}'")

We have to reassign the tracker that is missing, to do so we have to look at the key "Created By:	YggTorrent" (torrent["CreatedBy"] ?) et r√©assigner le tracker 
